#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SITE_CONFIG="${REPO_ROOT}/config/site.env"

echo "=== Viam Lab Provisioner Setup ==="
echo ""

if [[ -f "$SITE_CONFIG" ]]; then
    echo "config/site.env already exists."
    read -p "Overwrite? (y/n) [n]: " OVERWRITE
    [[ "$OVERWRITE" == "y" ]] || { echo "Keeping existing config."; exit 0; }
    echo ""
fi

# --- Machine batch ---

echo "Machine batch:"
read -p "  Hostname prefix [lab-pi]: " PREFIX
PREFIX="${PREFIX:-lab-pi}"
read -p "  How many machines? [10]: " COUNT
COUNT="${COUNT:-10}"
echo ""

# --- OS account ---

echo "OS account:"
read -p "  Username [viam]: " USERNAME
USERNAME="${USERNAME:-viam}"
read -p "  Password [checkmate]: " PASSWORD
PASSWORD="${PASSWORD:-checkmate}"
echo ""

# --- Network ---

echo "Network:"
read -p "  WiFi SSID (blank to skip): " WIFI_SSID
WIFI_PASSWORD=""
if [[ -n "$WIFI_SSID" ]]; then
    read -p "  WiFi password: " WIFI_PASSWORD
fi
read -p "  Timezone [America/New_York]: " TIMEZONE
TIMEZONE="${TIMEZONE:-America/New_York}"
echo ""

# --- SSH ---

echo "SSH access:"
echo "  Provisioned machines need an SSH public key so you can log in."
echo "  You can generate a dedicated keypair for these machines, or use"
echo "  an existing key."
echo ""

SSH_PUBLIC_KEY_FILE=""
read -p "  Generate a new keypair for '${PREFIX}-*' machines? (y/n) [y]: " GEN_KEY
GEN_KEY="${GEN_KEY:-y}"

if [[ "$GEN_KEY" == "y" ]]; then
    KEY_PATH="$HOME/.ssh/id_${PREFIX}"
    if [[ -f "$KEY_PATH" ]]; then
        echo "  Key already exists at ${KEY_PATH}"
    else
        echo "  Generating ${KEY_PATH}..."
        ssh-keygen -t ed25519 -f "$KEY_PATH" -N "" -C "${PREFIX}-provisioner"
    fi
    SSH_PUBLIC_KEY_FILE="${KEY_PATH}.pub"

    # Configure SSH client
    SSH_CONFIG="$HOME/.ssh/config"
    MATCH_PATTERN="${PREFIX}-*"
    if grep -q "Host ${MATCH_PATTERN}" "$SSH_CONFIG" 2>/dev/null; then
        echo "  SSH config already has a '${MATCH_PATTERN}' block."
    else
        echo ""
        echo "  Adding SSH config so 'ssh ${PREFIX}-<name>' just works:"
        echo "    Host ${MATCH_PATTERN}"
        echo "      User ${USERNAME}"
        echo "      IdentityFile ${KEY_PATH}"
        echo ""
        read -p "  Add this to ~/.ssh/config? (y/n) [y]: " ADD_SSH_CONFIG
        ADD_SSH_CONFIG="${ADD_SSH_CONFIG:-y}"
        if [[ "$ADD_SSH_CONFIG" == "y" ]]; then
            mkdir -p "$(dirname "$SSH_CONFIG")"
            cat >> "$SSH_CONFIG" <<SSHEOF

Host ${MATCH_PATTERN}
    User ${USERNAME}
    IdentityFile ${KEY_PATH}
SSHEOF
            chmod 600 "$SSH_CONFIG"
            echo "  Added to ${SSH_CONFIG}"
        fi
    fi
else
    read -p "  Path to existing SSH public key [~/.ssh/id_ed25519.pub]: " SSH_PUBLIC_KEY_FILE
    SSH_PUBLIC_KEY_FILE="${SSH_PUBLIC_KEY_FILE:-~/.ssh/id_ed25519.pub}"
    EXPANDED="${SSH_PUBLIC_KEY_FILE/#\~/$HOME}"
    if [[ ! -f "$EXPANDED" ]]; then
        echo "  WARNING: ${SSH_PUBLIC_KEY_FILE} not found. You'll need to fix this before flashing."
    fi
fi
echo ""

# --- Viam Cloud ---

echo "Viam Cloud:"
echo "  Provision modes:"
echo "    full    — create machines in Viam, install viam-agent, deploy credentials"
echo "    agent   — install viam-agent binary (users set up Viam themselves)"
echo "    os-only — just configure the OS, no Viam software"
echo ""
read -p "  Provision mode [os-only]: " PROVISION_MODE
PROVISION_MODE="${PROVISION_MODE:-os-only}"

VIAM_API_KEY_ID=""
VIAM_API_KEY=""
VIAM_ORG_ID=""
VIAM_LOCATION_ID=""

if [[ "$PROVISION_MODE" == "full" ]]; then
    echo ""
    echo "  You need a Viam API key with permission to create machines."
    echo "  Create one at app.viam.com > Organization Settings > API Keys."
    echo ""
    read -p "  API Key ID: " VIAM_API_KEY_ID
    read -p "  API Key: " VIAM_API_KEY
    read -p "  Organization ID: " VIAM_ORG_ID
    read -p "  Location ID: " VIAM_LOCATION_ID
fi
echo ""

# --- Tailscale ---

echo "Tailscale (optional):"
echo "  Provide an auth key to auto-join machines to your Tailscale network."
echo "  Generate one at: https://login.tailscale.com/admin/settings/keys"
echo ""
read -p "  Tailscale auth key (blank to skip): " TAILSCALE_AUTH_KEY
TAILSCALE_AUTH_KEY="${TAILSCALE_AUTH_KEY:-}"
echo ""

# --- Write config ---

cat > "$SITE_CONFIG" <<EOF
# Site configuration — generated by setup-wizard
# Re-run 'just setup-wizard' to regenerate, or edit directly.

# Machine batch
PREFIX=${PREFIX}
COUNT=${COUNT}

# OS account
USERNAME=${USERNAME}
PASSWORD=${PASSWORD}

# Network
WIFI_SSID=${WIFI_SSID}
WIFI_PASSWORD=${WIFI_PASSWORD}
TIMEZONE=${TIMEZONE}

# SSH
SSH_PUBLIC_KEY_FILE=${SSH_PUBLIC_KEY_FILE}

# Viam Cloud
PROVISION_MODE=${PROVISION_MODE}
VIAM_API_KEY_ID=${VIAM_API_KEY_ID}
VIAM_API_KEY=${VIAM_API_KEY}
VIAM_ORG_ID=${VIAM_ORG_ID}
VIAM_LOCATION_ID=${VIAM_LOCATION_ID}

# Tailscale
TAILSCALE_AUTH_KEY=${TAILSCALE_AUTH_KEY}
EOF

echo "Written to config/site.env"
echo ""
echo "=== Next steps ==="
echo "  1. Download Pi OS image:  just download-pi-image"
echo "  2. Flash SD cards:        just flash-batch"
if [[ "$PROVISION_MODE" == "full" ]]; then
    echo ""
    echo "  For PXE (x86 machines):"
    echo "  1. Extract ISO:           just setup"
    echo "  2. Generate autoinstall:  just build-config"
    echo "  3. Start services:        just up && just dhcp"
    echo "  4. Provision batch:       just provision config/site.env"
    echo "  5. Start watcher:         just watch"
fi
